const marketSeed = {
  IDN:{name:'إندونيسيا',quota:241000,applicants:318000,entries:232400,umrah:1680000,basePrice:23800},
  PAK:{name:'باكستان',quota:180000,applicants:256000,entries:171800,umrah:1190000,basePrice:21900},
  IND:{name:'الهند',quota:175000,applicants:228000,entries:168300,umrah:930000,basePrice:26700},
  BGD:{name:'بنغلاديش',quota:127000,applicants:183000,entries:119500,umrah:610000,basePrice:24500},
  NGA:{name:'نيجيريا',quota:95000,applicants:131000,entries:88400,umrah:310000,basePrice:30400},
  TUR:{name:'تركيا',quota:83000,applicants:98000,entries:80600,umrah:520000,basePrice:28500},
  EGY:{name:'مصر',quota:78000,applicants:106000,entries:75200,umrah:740000,basePrice:19600},
  IRN:{name:'إيران',quota:87000,applicants:112000,entries:82900,umrah:480000,basePrice:23200},
  DZA:{name:'الجزائر',quota:41000,applicants:67000,entries:39700,umrah:390000,basePrice:27800},
  MAR:{name:'المغرب',quota:34000,applicants:59000,entries:32600,umrah:350000,basePrice:28900},
  MYS:{name:'ماليزيا',quota:32000,applicants:68000,entries:31500,umrah:440000,basePrice:31900},
  IRQ:{name:'العراق',quota:50000,applicants:74000,entries:47100,umrah:460000,basePrice:20500},
  JOR:{name:'الأردن',quota:12000,applicants:24000,entries:11600,umrah:265000,basePrice:18100},
  SDN:{name:'السودان',quota:32000,applicants:47000,entries:28200,umrah:180000,basePrice:22100},
  ETH:{name:'إثيوبيا',quota:14000,applicants:21000,entries:12800,umrah:95000,basePrice:24600},
  UZB:{name:'أوزبكستان',quota:15000,applicants:27000,entries:14600,umrah:160000,basePrice:27600},
  KAZ:{name:'كازاخستان',quota:4000,applicants:8500,entries:3900,umrah:74000,basePrice:29500},
  GBR:{name:'المملكة المتحدة',quota:18000,applicants:31000,entries:17200,umrah:210000,basePrice:38700},
  FRA:{name:'فرنسا',quota:15000,applicants:26000,entries:14200,umrah:180000,basePrice:36500},
  USA:{name:'الولايات المتحدة',quota:13000,applicants:23000,entries:12400,umrah:145000,basePrice:42500},
};
const localeName=new Intl.DisplayNames(['ar'],{type:'region'});
const dummySeasonProfiles={
  1447:{quota:1,applicants:1,entries:1,umrah:1,price:1,growth:0},
  1446:{quota:.965,applicants:.925,entries:.957,umrah:.91,price:.95,growth:-1.4},
  1445:{quota:.925,applicants:.855,entries:.91,umrah:.82,price:.9,growth:-2.6},
};
const number=new Intl.NumberFormat('en-US',{maximumFractionDigits:0});
const usd=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:1});
const sar=n=>`${number.format(Math.round(n))} ر.س`;
const safe=n=>Number.isFinite(Number(n))?Number(n):0;
const pct=n=>`${Math.round(n)}%`;
const compact={format(n){const v=safe(n),a=Math.abs(v);if(a>=1e9)return `${(v/1e9).toFixed(1).replace('.0','')} مليار`;if(a>=1e6)return `${(v/1e6).toFixed(1).replace('.0','')} مليون`;if(a>=1e3)return `${(v/1e3).toFixed(1).replace('.0','')} ألف`;return number.format(v)}};
const [worldBank,dictionary]=await Promise.all([
  fetch('./data/world-bank-countries.json').then(r=>r.json()),
  fetch('./data/data-dictionary.json').then(r=>r.json()),
]);
let season='1447',countryPage=1,currentCountries=[],compareCodes=[],compareCategory='general',comparePackageTrip='hajj',comparePackageTier='متوازنة';
const PAGE_SIZE=18;
const countryByCode=Object.fromEntries(worldBank.map(c=>[c.iso3_code,c]));

function marketForSeason(code,selectedSeason=season){
  const base=marketSeed[code]; if(!base)return null;
  const profile=dummySeasonProfiles[selectedSeason],countryVariation=selectedSeason==='1447'?0:((code.charCodeAt(0)+code.charCodeAt(2))%5-2)/100;
  const quota=Math.round(base.quota*(profile.quota+countryVariation/2)),applicants=Math.round(base.applicants*(profile.applicants+countryVariation)),entries=Math.min(quota,Math.round(base.entries*(profile.entries+countryVariation/2))),umrah=Math.round(base.umrah*(profile.umrah+countryVariation));
  return {...base,quota,applicants,entries,umrah,basePrice:Math.round(base.basePrice*profile.price/50)*50,growth:Number((4+(code.charCodeAt(0)%7)+profile.growth).toFixed(1))};
}
function marketFor(code){return marketForSeason(code,season)}
function arabicName(country){try{return localeName.of(country.iso2_code)||country.country_name_en}catch{return country.country_name_en}}
function showToast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.classList.remove('show'),2400)}
function switchView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-link').forEach(v=>v.classList.toggle('active',v.dataset.view===id));document.querySelector('#main-nav').classList.remove('open');if(id==='overview')renderOverview();if(id==='umrah')renderUmrah();window.scrollTo({top:0,behavior:'smooth'});}

document.querySelectorAll('.nav-link').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));
document.querySelectorAll('[data-go]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.go)));
document.querySelector('#mobile-menu').addEventListener('click',()=>document.querySelector('#main-nav').classList.toggle('open'));
document.querySelector('#season-select').addEventListener('change',event=>{season=event.target.value;renderMarketViews();showToast(`تم عرض بيانات الموسم التجريبي ${season} هـ`)});

function renderOverview(){
  const markets=Object.keys(marketSeed).map(code=>({code,...marketFor(code)})).sort((a,b)=>b.quota-a.quota);
  const totalQuota=markets.reduce((s,m)=>s+m.quota,0),totalEntries=markets.reduce((s,m)=>s+m.entries,0),totalUmrah=markets.reduce((s,m)=>s+m.umrah,0),totalApplicants=markets.reduce((s,m)=>s+m.applicants,0);
  document.querySelector('#executive-brief').innerHTML=`<div class="brief-item"><strong>${markets[0].name} أكبر دولة في البيانات المتاحة</strong><span>${number.format(markets[0].quota)} حصة تجريبية</span></div><div class="brief-item"><strong>${pct(totalEntries/totalQuota*100)} معدل استغلال الحصص</strong><span>${compact.format(totalEntries)} دخول فعلي</span></div><div class="brief-item"><strong>${[...markets].sort((a,b)=>b.growth-a.growth)[0].name} الأعلى نموًا</strong><span>إشارة تجريبية وليست توقعًا رسميًا</span></div>`;
  const previousSeason=season==='1447'?'1446':season==='1446'?'1445':null,previousUmrah=previousSeason?Object.keys(marketSeed).reduce((s,c)=>s+marketForSeason(c,previousSeason).umrah,0):0,umrahChange=previousSeason?(totalUmrah-previousUmrah)/previousUmrah*100:0;
  document.querySelector('#metric-ribbon').innerHTML=metricHTML([['متقدمو الحج',compact.format(totalApplicants),`موسم ${season} هـ`],['الدخول الفعلي للحج',compact.format(totalEntries),pct(totalEntries/totalQuota*100)+' استغلال الحصة'],['إجمالي المعتمرين',compact.format(totalUmrah),'للدول ذات البيانات التجريبية'],['تغير العمرة',previousSeason?pct(umrahChange):'—',previousSeason?`مقابل ${previousSeason} هـ`:'لا يتوفر موسم سابق']]);
  const top=markets.sort((a,b)=>b.quota-a.quota).slice(0,8),max=top[0].quota;
  document.querySelector('#market-bars').innerHTML=top.map(m=>`<div class="quota-row"><strong>${m.name}</strong><div class="quota-series"><div><span>الحصة</span><i class="quota-fill" style="width:${m.quota/max*100}%"></i><b>${number.format(m.quota)}</b></div><div><span>الدخول</span><i class="entry-fill" style="width:${m.entries/max*100}%"></i><b>${number.format(m.entries)}</b></div></div><small>${pct(m.entries/m.quota*100)} استغلال الحصة</small></div>`).join('');
  const signals=[...markets].sort((a,b)=>(b.applicants/b.quota)-(a.applicants/a.quota)).slice(0,4);
  document.querySelector('#signals').innerHTML=signals.map(m=>{const gap=(m.applicants-m.quota)/m.quota*100;return `<div class="demand-card"><div><strong>${m.name}</strong><small>نسبة زيادة المتقدمين عن الحصة</small></div><b>${pct(gap)}</b><div class="demand-values"><span>المتقدمون ${number.format(m.applicants)}</span><span>الحصة ${number.format(m.quota)}</span></div></div>`}).join('');
  const regionCounts={};markets.forEach(m=>{const r=countryByCode[m.code]?.region_name_en||'غير مصنف';regionCounts[r]=(regionCounts[r]||0)+1});renderDonut('overview-donut',regionCounts,'توزيع','حسب المنطقة');
}
function metricHTML(items){return items.map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('')}
const chartColors=['#038061','#d7a562','#174766','#70a3c2','#87452b','#d6dee5','#2b140a'];
function regionLabel(name){return ({'Middle East, North Africa, Afghanistan & Pakistan':'الشرق الأوسط وشمال أفريقيا','Europe & Central Asia':'أوروبا وآسيا الوسطى','South Asia':'جنوب آسيا','Sub-Saharan Africa':'أفريقيا جنوب الصحراء','East Asia & Pacific':'شرق آسيا والمحيط الهادئ','North America':'أمريكا الشمالية','Latin America & Caribbean':'أمريكا اللاتينية'})[name]||name}
function renderDonut(id,groups,centerValue,centerLabel){const entries=Object.entries(groups).sort((a,b)=>b[1]-a[1]),total=entries.reduce((s,x)=>s+x[1],0)||1;let angle=0;const stops=entries.map((x,i)=>{const start=angle;angle+=x[1]/total*360;return `${chartColors[i%chartColors.length]} ${start}deg ${angle}deg`});const isVolume=total>1000;document.querySelector(`#${id}`).innerHTML=`<div class="donut" style="background:conic-gradient(${stops.join(',')})"><div><strong>${centerValue||compact.format(total)}</strong><span>${centerLabel||'الإجمالي'}</span></div></div><div class="donut-legend">${entries.map((x,i)=>`<span><i style="background:${chartColors[i%chartColors.length]}"></i>${regionLabel(x[0])} <b>${isVolume?compact.format(x[1]):number.format(x[1])}</b></span>`).join('')}</div>`}
function drawLineChart(id,values,labels){requestAnimationFrame(()=>{const root=document.querySelector(`#${id}`),canvas=root?.querySelector('canvas');if(!canvas)return;const width=Math.max(320,root.clientWidth),height=220,ratio=window.devicePixelRatio||1;canvas.width=width*ratio;canvas.height=height*ratio;canvas.style.width='100%';canvas.style.height=`${height}px`;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);const pad={x:48,y:28,b:35},max=Math.max(...values)*1.08,min=Math.min(...values)*.9,points=values.map((v,i)=>({x:pad.x+i*(width-pad.x*2)/(values.length-1),y:height-pad.b-(v-min)/(max-min)*(height-pad.y-pad.b)}));ctx.strokeStyle='#dce2de';ctx.lineWidth=1;for(let i=0;i<4;i++){const y=pad.y+i*(height-pad.y-pad.b)/3;ctx.beginPath();ctx.moveTo(pad.x,y);ctx.lineTo(width-pad.x,y);ctx.stroke()}ctx.strokeStyle='#038061';ctx.lineWidth=4;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.fillStyle='#d7a562';points.forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,6,0,Math.PI*2);ctx.fill()});ctx.textAlign='center';ctx.font='12px Abar';points.forEach((p,i)=>{ctx.fillStyle='#65716e';ctx.fillText(labels[i],p.x,height-10);ctx.fillStyle='#101817';ctx.fillText(compact.format(values[i]),p.x,p.y-13)})})}

function populateFilters(){
  const regions=[...new Set(worldBank.map(c=>c.region_name_en).filter(Boolean))].sort();
  const incomes=[...new Set(worldBank.map(c=>c.income_level_name_en).filter(Boolean))].sort();
  document.querySelector('#region-filter').innerHTML+=[...regions].map(v=>`<option value="${v}">${v}</option>`).join('');
  document.querySelector('#income-filter').innerHTML+=[...incomes].map(v=>`<option value="${v}">${v}</option>`).join('');
  document.querySelector('#package-country').innerHTML+=Object.keys(marketSeed).map(code=>`<option value="${code}">${marketSeed[code].name}</option>`).join('');
  document.querySelector('#compare-country-add').innerHTML='<option value="">اختر دولة</option>'+Object.keys(marketSeed).map(code=>`<option value="${code}">${marketSeed[code].name}</option>`).join('');
}
function normalizeArabic(value){return String(value||'').toLowerCase().normalize('NFKD').replace(/\p{M}/gu,'').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[ؤئ]/g,'ء').replace(/[ًٌٍَُِّْـ]/g,'').replace(/[^a-z0-9\u0600-\u06ff]/g,'')}
function editDistance(a,b){const x=normalizeArabic(a),y=normalizeArabic(b),row=Array.from({length:y.length+1},(_,i)=>i);for(let i=1;i<=x.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=y.length;j++){const temp=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,prev+(x[i-1]===y[j-1]?0:1));prev=temp}}return row[y.length]}
function searchMatch(country,query){if(!query)return true;const q=normalizeArabic(query),names=[arabicName(country),country.country_name_en,country.iso3_code].map(normalizeArabic);return names.some(n=>n.includes(q)||q.includes(n)||(q.length>=4&&editDistance(n,q)<=Math.max(1,Math.floor(q.length/5))))}
function searchScore(country,query){const q=normalizeArabic(query),names=[arabicName(country),country.country_name_en,country.iso3_code].map(normalizeArabic);let best=99;for(const n of names){if(n.startsWith(q))best=Math.min(best,0);else if(n.includes(q))best=Math.min(best,1);else if(q.length>=3&&n[0]===q[0])best=Math.min(best,2+editDistance(n,q)/Math.max(n.length,q.length))}return best}
function filteredCountries(){
  const q=document.querySelector('#country-search').value.trim(),region=document.querySelector('#region-filter').value,income=document.querySelector('#income-filter').value,type=document.querySelector('#market-filter').value;
  return worldBank.filter(c=>{const isMarket=!!marketSeed[c.iso3_code];return searchMatch(c,q)&&(region==='all'||c.region_name_en===region)&&(income==='all'||c.income_level_name_en===income)&&(type==='all'||(type==='market'&&isMarket)||(type==='general'&&!isMarket));}).sort((a,b)=>q?(searchScore(a,q)-searchScore(b,q))||((marketSeed[b.iso3_code]?1:0)-(marketSeed[a.iso3_code]?1:0)):0);
}
function renderCountries(reset=false){
  if(reset)countryPage=1;currentCountries=filteredCountries();const pages=Math.max(1,Math.ceil(currentCountries.length/PAGE_SIZE));countryPage=Math.min(countryPage,pages);const rows=currentCountries.slice((countryPage-1)*PAGE_SIZE,countryPage*PAGE_SIZE);
  document.querySelector('#country-count').textContent=number.format(currentCountries.length);
  const query=document.querySelector('#country-search').value.trim(),suggestion=document.querySelector('#search-suggestion');
  if(query&&currentCountries.length===0){const closest=worldBank.map(c=>({c,score:searchScore(c,query)})).sort((a,b)=>a.score-b.score)[0],valid=normalizeArabic(query).length>=3&&closest&&closest.score<2.55;suggestion.textContent=valid?`هل تقصد: ${arabicName(closest.c)}؟`:'لا توجد نتائج قريبة';suggestion.dataset.code=valid?closest.c.iso3_code:''}else suggestion.textContent='';
  document.querySelector('#country-table').innerHTML=rows.map(c=>`<tr data-code="${c.iso3_code}"><td><div class="country-name"><span class="code-token">${c.iso3_code}</span><div><strong>${arabicName(c)}</strong><small>${c.country_name_en}</small></div></div></td><td>${c.region_name_en||'—'}</td><td>${c.population_total?compact.format(c.population_total):'—'}</td><td>${c.gdp_current_usd?usd.format(c.gdp_current_usd):'—'}</td><td>${c.gni_per_capita_usd?usd.format(c.gni_per_capita_usd):'—'}</td><td>${c.gdp_current_usd_year||c.population_total_year||'—'}</td><td>${marketSeed[c.iso3_code]?'<span class="market-badge">تتوفر بيانات حج وعمرة</span>':'<span class="general-badge">بيانات عامة</span>'}</td></tr>`).join('');
  document.querySelectorAll('#country-table tr').forEach(r=>r.onclick=()=>openCountry(r.dataset.code));
  document.querySelector('#table-summary').textContent=`عرض ${rows.length} من ${currentCountries.length} نتيجة`;
  document.querySelector('#page-number').textContent=`${countryPage} / ${pages}`;document.querySelector('#prev-page').disabled=countryPage===1;document.querySelector('#next-page').disabled=countryPage===pages;
}
['country-search','region-filter','income-filter','market-filter'].forEach(id=>document.querySelector(`#${id}`).addEventListener(id==='country-search'?'input':'change',()=>renderCountries(true)));
document.querySelector('#clear-filters').onclick=()=>{document.querySelector('#country-search').value='';document.querySelector('#region-filter').value='all';document.querySelector('#income-filter').value='all';document.querySelector('#market-filter').value='all';syncCustomSelects();renderCountries(true)};
document.querySelector('#search-suggestion').onclick=()=>{const code=document.querySelector('#search-suggestion').dataset.code,c=countryByCode[code];if(c){document.querySelector('#country-search').value=arabicName(c);renderCountries(true)}};
document.querySelector('#prev-page').onclick=()=>{countryPage--;renderCountries()};document.querySelector('#next-page').onclick=()=>{countryPage++;renderCountries()};

function renderHajj(){
  const markets=Object.keys(marketSeed).map(code=>({code,...marketFor(code)})).sort((a,b)=>b.quota-a.quota),totals=markets.reduce((a,m)=>({applicants:a.applicants+m.applicants,quota:a.quota+m.quota,entries:a.entries+m.entries}),{applicants:0,quota:0,entries:0});
  const top=markets.slice(0,10),max=top[0].quota;document.querySelector('#hajj-bars').innerHTML=top.map(m=>`<div class="hbar-row"><span>${m.name}</span><div class="hbar-track"><i style="width:${m.quota/max*100}%"><b>${compact.format(m.quota)}</b></i></div><strong>${pct(m.entries/m.quota*100)}</strong></div>`).join('');
  const conversion=[['المتقدمون',totals.applicants,'إجمالي الطلب',100],['الحصص',totals.quota,`فجوة الطلب ${compact.format(totals.applicants-totals.quota)}`,totals.quota/totals.applicants*100],['الدخول الفعلي',totals.entries,`غير مستغل ${compact.format(totals.quota-totals.entries)}`,totals.entries/totals.applicants*100]];
  document.querySelector('#hajj-conversion').innerHTML=conversion.map((x,i)=>`<div class="conversion-row"><div><span>${x[0]}</span><strong>${compact.format(x[1])}</strong></div><div class="conversion-track"><i class="stage-${i}" style="width:${x[3]}%"></i></div><small>${x[2]}</small></div>`).join('');
  document.querySelector('#hajj-table').innerHTML=markets.map(m=>`<tr><td>${m.name}</td><td>${number.format(m.applicants)}</td><td>${number.format(m.quota)}</td><td>${number.format(m.entries)}</td><td>${pct(m.entries/m.quota*100)}</td><td><span class="confidence medium">تجريبية</span></td></tr>`).join('');
}
function renderUmrah(){
  const markets=Object.keys(marketSeed).map(code=>({code,...marketFor(code)})).sort((a,b)=>b.umrah-a.umrah),total=markets.reduce((s,m)=>s+m.umrah,0),avg=markets.reduce((s,m)=>s+m.growth,0)/markets.length;
  document.querySelector('#umrah-kpis').innerHTML=metricHTML([['إجمالي البيانات المتاحة',compact.format(total),'بيانات تجريبية'],['متوسط النمو',pct(avg),'إشارة تجريبية'],['أكبر دولة',markets[0].name,compact.format(markets[0].umrah)],['دول فوق المتوسط',number.format(markets.filter(m=>m.growth>avg).length),'وفق معدل النمو']]);
  const top=markets.slice(0,9),max=top[0].umrah;document.querySelector('#umrah-columns').innerHTML=top.map(m=>`<div class="lollipop-row"><span>${m.name}</span><div class="lollipop-track"><i style="width:${m.umrah/max*100}%"><b></b></i></div><strong>${compact.format(m.umrah)}</strong></div>`).join('');
  const months=['محرم','صفر','ربيع الأول','ربيع الآخر','جمادى الأولى','جمادى الآخرة','رجب','شعبان','رمضان','شوال','ذو القعدة','ذو الحجة'],values=[42,38,49,55,58,66,79,91,100,48,32,18];document.querySelector('#seasonality').innerHTML=months.map((m,i)=>`<div class="month-column ${values[i]>85?'peak':''}"><i style="height:${values[i]}%"></i><span>${m}</span></div>`).join('');
  const regional={};markets.forEach(m=>{const r=countryByCode[m.code]?.region_name_en||'غير مصنف';regional[r]=(regional[r]||0)+m.umrah});renderDonut('umrah-region-donut',regional);
  const packages=allPackages('umrah').filter(p=>p.tier==='متوازنة');document.querySelector('#umrah-package-gap').innerHTML=packageColumnsHTML(packages,5);const avgGap=packages.reduce((s,p)=>s+p.gapPct,0)/packages.length,peak='رمضان',largest=markets[0],highest=[...packages].sort((a,b)=>b.gapPct-a.gapPct)[0];document.querySelector('#umrah-insights').innerHTML=`<div><strong>${largest.name} الأعلى حجمًا</strong><span>${compact.format(largest.umrah)} معتمر في الموسم المختار</span></div><div><strong>${peak} شهر الذروة</strong><span>وفق التوزيع الموسمي التجريبي</span></div><div><strong>${pct(avgGap)} متوسط فجوة السعر</strong><span>${highest.country} تسجل أعلى فجوة ضمن المستوى المتوازن</span></div>${formulaNote('نسبة فجوة السعر = (الدفع الفعلي − السعر المعلن) ÷ السعر المعلن × 100. المتوسط = مجموع نسب الفجوة ÷ عدد الباقات.')}`;
}
function renderCompare(){
  const list=compareCodes.map(code=>({code,country:countryByCode[code],market:marketFor(code)}));
  document.querySelector('#compare-chips').innerHTML=compareCodes.map(code=>`<span class="compare-chip">${marketSeed[code].name}<button data-remove-country="${code}" aria-label="حذف ${marketSeed[code].name}">×</button></span>`).join('');
  const clearButton=document.querySelector('#clear-compare-countries');clearButton.hidden=compareCodes.length===0;
  document.querySelectorAll('[data-remove-country]').forEach(btn=>btn.onclick=()=>{compareCodes=compareCodes.filter(c=>c!==btn.dataset.removeCountry);renderCompare()});
  document.querySelector('#compare-country-add').innerHTML='<option value="">اختر دولة</option>'+Object.keys(marketSeed).filter(code=>!compareCodes.includes(code)).map(code=>`<option value="${code}">${marketSeed[code].name}</option>`).join('');
  const enough=list.length>=2;document.querySelector('#compare-empty').style.display=enough?'none':'grid';
  const chosenPackages=Object.fromEntries(allPackages(comparePackageTrip).filter(p=>p.tier===comparePackageTier).map(p=>[p.code,p]));
  const definitions={general:{explain:'رسوم متنوعة للقيم الفعلية. تظهر سنة كل مؤشر ومصدره دون تحويل القيم إلى درجة موحّدة.',metrics:[['السكان',x=>safe(x.country.population_total),compact.format,x=>x.country.population_total_year,'البنك الدولي'],['GDP',x=>safe(x.country.gdp_current_usd),usd.format,x=>x.country.gdp_current_usd_year,'البنك الدولي'],['دخل الفرد',x=>safe(x.country.gni_per_capita_usd),usd.format,x=>x.country.gni_per_capita_usd_year,'البنك الدولي'],['استخدام الإنترنت',x=>safe(x.country.internet_users_pct),pct,x=>x.country.internet_users_pct_year,'البنك الدولي']]},hajj:{explain:`قيم الموسم ${season} هـ التجريبية، وتتغير مع محدد الموسم أعلى الصفحة.`,metrics:[['المتقدمون',x=>x.market.applicants,number.format,()=>season,'بيانات تجريبية'],['الحصة',x=>x.market.quota,number.format,()=>season,'بيانات تجريبية'],['الدخول الفعلي',x=>x.market.entries,number.format,()=>season,'بيانات تجريبية'],['استغلال الحصة',x=>x.market.entries/x.market.quota*100,pct,()=>season,'بيانات تجريبية']]},umrah:{explain:`قيم الموسم ${season} هـ التجريبية، مع سلسلة مستقلة لا تمثل توقعًا رسميًا.`,metrics:[['المعتمرون',x=>x.market.umrah,compact.format,()=>season,'بيانات تجريبية'],['النمو التجريبي',x=>x.market.growth,pct,()=>season,'بيانات تجريبية']]},packages:{explain:`أنت تقارن الآن باقات ${comparePackageTrip==='hajj'?'الحج':'العمرة'} — المستوى ${comparePackageTier}. الاختيار من المستخدم ولا توجد درجة إجمالية.`,metrics:[['السعر',x=>chosenPackages[x.code].price,sar,()=>'—','بيانات تجريبية'],['مدة البرنامج',x=>chosenPackages[x.code].nights,x=>`${number.format(x)} ليلة`,()=>'—','بيانات تجريبية'],['تصنيف الفندق',x=>chosenPackages[x.code].hotel,x=>`${number.format(x)} نجوم`,()=>'—','بيانات تجريبية'],['المسافة',x=>chosenPackages[x.code].distance,x=>`${number.format(x)} م`,()=>'—','بيانات تجريبية']]}};
  const selected=definitions[compareCategory],comparisonCopy={general:'أشكال مختلفة تناسب كل مؤشر عام، مع القيمة والسنة من البنك الدولي.',hajj:`مقارنة رحلة الحاج من الطلب إلى الدخول · موسم ${season} هـ · بيانات تجريبية.`,umrah:'اتجاه حجم العمرة عبر المواسم الثلاثة، مع إبراز الموسم المختار.',packages:`باقات ${comparePackageTrip==='hajj'?'الحج':'العمرة'} — المستوى ${comparePackageTier}: السعر المعلن مقابل الدفع الفعلي.`};document.querySelector('#comparison-explanation').textContent=comparisonCopy[compareCategory];
  document.querySelector('#compare-package-controls').hidden=compareCategory!=='packages';
  document.querySelector('#compare-matrix').style.display=enough?'grid':'none';
  if(!enough)return;
  renderComparisonCharts(list,chosenPackages);
}
function chartPanel(title,meta,content,extra=''){return `<article class="analysis-panel compare-chart-panel ${extra}" data-chart-title="${title}"><div class="panel-heading"><div><h2>${title}</h2><small>${meta}</small></div></div>${content}</article>`}
function verticalColumns(list,get,format){const max=Math.max(...list.map(get),1);return `<div class="vbar-chart"><div class="vbar-scale"><span>${format(max)}</span><span>${format(max*.75)}</span><span>${format(max*.5)}</span><span>${format(max*.25)}</span><span>0</span></div><div class="compare-vbars">${list.map((x,i)=>`<div><div class="vbar-column"><strong>${format(get(x))}</strong><i style="height:${Math.max(12,get(x)/max*100)}%;background:${chartColors[i%chartColors.length]}"></i></div><span>${x.market.name}</span></div>`).join('')}</div></div>`}
function horizontalBars(list,get,format){const max=Math.max(...list.map(get),1);return `<div class="compare-hbars">${list.map((x,i)=>`<div><span>${x.market.name}</span><i><b style="width:${get(x)/max*100}%;background:${chartColors[i%chartColors.length]}"></b></i><strong>${format(get(x))}</strong></div>`).join('')}</div>`}
function treemapValues(list,get,format){const total=list.reduce((s,x)=>s+get(x),0)||1;return `<div class="compare-treemap">${[...list].sort((a,b)=>get(b)-get(a)).map((x,i)=>`<div style="flex-grow:${Math.max(get(x),1)};background:${chartColors[i%chartColors.length]}" aria-label="${x.market.name}: ${format(get(x))}"><strong>${x.market.name}</strong><span>${format(get(x))}</span><small>${pct(get(x)/total*100)} من إجمالي الدول المختارة</small></div>`).join('')}</div>${formulaNote('حصة كل دولة في الشكل = قيمة الناتج المحلي للدولة ÷ مجموع الناتج المحلي للدول المختارة × 100.')}`}
function pairedPercent(list){return `<div class="percent-columns"><div class="chart-legend"><span><i class="internet-key"></i> الإنترنت</span><span><i class="urban-key"></i> التحضر</span></div><div class="percent-column-plot">${list.map(x=>{const internet=safe(x.country.internet_users_pct),urban=safe(x.country.urban_population_pct);return `<div class="percent-country"><div class="percent-pair"><i class="internet" style="height:${internet}%"><b>${pct(internet)}</b></i><i class="urban" style="height:${urban}%"><b>${pct(urban)}</b></i></div><strong>${x.market.name}</strong></div>`}).join('')}</div><div class="percent-scale"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div></div>`}
function hajjGrouped(list){const series=[['المتقدمون','applicants','app'],['الحصة','quota','quota'],['الدخول الفعلي','entries','entry']],max=Math.max(...list.map(x=>x.market.applicants),1);return `<p class="chart-reading"><strong>كيف يُقرأ؟</strong> لكل دولة ثلاثة أعمدة: الطلب الكلي، الحصة المتاحة، ثم من دخل فعليًا. الفرق بين الأول والثاني يوضح ضغط الطلب، والفرق بين الثاني والثالث يوضح الجزء غير المستغل من الحصة.</p><div class="hajj-column-legend">${series.map(s=>`<span><i class="${s[2]}"></i>${s[0]}</span>`).join('')}</div><div class="hajj-column-chart">${list.map(x=>`<div class="hajj-country-group"><div class="hajj-columns">${series.map(s=>`<i class="${s[2]}" style="height:${Math.max(18,x.market[s[1]]/max*230)}px"><b>${compact.format(x.market[s[1]])}</b></i>`).join('')}</div><strong>${x.market.name}</strong></div>`).join('')}</div>`}
function umrahLines(list){
  const seasons=['1445','1446','1447'];
  const series=list.map((x,i)=>{
    const values=seasons.map(s=>marketForSeason(x.code,s).umrah),base=Math.max(values[0],1),indexes=values.map(v=>v/base*100);
    return{x,i,values,indexes,color:chartColors[i%chartColors.length]};
  });
  const ceiling=Math.ceil(Math.max(110,...series.flatMap(s=>s.indexes))/10)*10;
  const axis=[ceiling,Math.round(ceiling*.75),Math.round(ceiling*.5),Math.round(ceiling*.25),0];
  return `<p class="chart-reading"><strong>منهجية المقارنة:</strong> يُقاس نمو كل سوق انطلاقًا من موسم الأساس 1445 هـ (المؤشر = 100)، بينما تعرض القيم أعلى الأعمدة العدد الفعلي للمعتمرين؛ وبذلك يوضح الرسم اتجاه النمو وحجم كل سوق معًا.</p><div class="umrah-growth-legend">${series.map(s=>`<span><i style="background:${s.color}"></i><strong>${s.x.market.name}</strong><b>${pct(s.indexes[2]-100)} نمو</b></span>`).join('')}</div><div class="umrah-growth-chart"><div class="umrah-growth-scale">${axis.map(v=>`<span>${v}</span>`).join('')}</div><div class="umrah-growth-plot">${seasons.map((season,seasonIndex)=>`<div class="umrah-season-group">${series.map(s=>`<i class="umrah-growth-column" style="height:${s.indexes[seasonIndex]/ceiling*100}%;background:${s.color}"><b>${compact.format(s.values[seasonIndex])}</b><span>${s.x.market.name} · ${season} هـ<br>عدد المعتمرين: ${compact.format(s.values[seasonIndex])}<br>مؤشر النمو: ${Math.round(s.indexes[seasonIndex])}</span></i>`).join('')}<strong class="umrah-season-label">${season} هـ</strong></div>`).join('')}</div></div>`;
}
function umrahPie(list){const total=list.reduce((s,x)=>s+x.market.umrah,0)||1,parts=list.map((x,i)=>({name:x.market.name,value:x.market.umrah,pct:x.market.umrah/total*100,color:chartColors[i%chartColors.length]})),stops=[];let cursor=0;parts.forEach(p=>{stops.push(`${p.color} ${cursor}% ${cursor+p.pct}%`);cursor+=p.pct});return `<p class="chart-reading"><strong>كيف يُقرأ؟</strong> الدائرة توضح حصة كل دولة من مجموع المعتمرين للدول المختارة في الموسم ${season} هـ. كلما كبر القطاع زادت مساهمة الدولة في الإجمالي.</p><div class="umrah-pie-layout"><div class="umrah-pie" style="background:conic-gradient(${stops.join(',')})"><div><strong>${compact.format(total)}</strong><span>الإجمالي</span></div></div><div class="umrah-pie-legend">${parts.sort((a,b)=>b.value-a.value).map(p=>`<div><i style="background:${p.color}"></i><strong>${p.name}</strong><span>${compact.format(p.value)}</span><b>${pct(p.pct)}</b></div>`).join('')}</div></div>${formulaNote('حصة الدولة = عدد معتمري الدولة ÷ مجموع معتمري الدول المختارة × 100.')}`}
function renderComparisonCharts(list,chosenPackages){const root=document.querySelector('#compare-matrix');root.className=`compare-visuals ${compareCategory==='general'?'general-layout':''}`;if(compareCategory==='general'){root.innerHTML=chartPanel('السكان','أعمدة رأسية مع محور قياس · البنك الدولي',verticalColumns(list,x=>safe(x.country.population_total),compact.format))+chartPanel('الناتج المحلي GDP','مساحة كل كتلة تمثل حصتها من إجمالي الدول المختارة',treemapValues(list,x=>safe(x.country.gdp_current_usd),usd.format))+chartPanel('دخل الفرد','ترتيب مباشر بالقيم الفعلية · البنك الدولي',horizontalBars(list,x=>safe(x.country.gni_per_capita_usd),usd.format))+chartPanel('الإنترنت والتحضر','نسب من 0 إلى 100% مع خط لكل 25%',pairedPercent(list),'percent-wide');return}if(compareCategory==='hajj'){root.innerHTML=chartPanel('من الطلب إلى الدخول',`الموسم ${season} هـ`,hajjGrouped(list),'wide-chart')+chartPanel('فجوة الطلب','زيادة المتقدمين عن الحصة',horizontalBars(list,x=>(x.market.applicants-x.market.quota)/x.market.quota*100,pct)+formulaNote('فجوة الطلب = (المتقدمون − الحصة) ÷ الحصة × 100.'),'wide-chart demand-gap-chart');return}if(compareCategory==='umrah'){root.innerHTML=chartPanel('اتجاه العمرة عبر المواسم','أعمدة نمو مجمّعة · موسم 1445 هـ = مؤشر 100',umrahLines(list),'wide-chart')+chartPanel('توزيع حجم الموسم المختار',`${season} هـ`,umrahPie(list),'wide-chart');return}const rows=list.map(x=>chosenPackages[x.code]);root.innerHTML=chartPanel('السعر المعلن مقابل الدفع الفعلي','الذهبي هو المعلن، والأخضر هو ما دُفع بعد الإضافات',packageColumnsHTML(rows,list.length),'wide-chart')+chartPanel('تفصيل الزيادة فوق السعر المعلن','يعرض توزيع الفجوة فقط حتى تظهر مكوناتها بوضوح',costCompositionHTML(rows,list.length),'wide-chart');}
document.querySelector('#add-compare-country').onclick=()=>{const code=document.querySelector('#compare-country-add').value;if(!code)return showToast('اختر دولة أولًا');if(compareCodes.length>=4)return showToast('الحد الأعلى أربع دول');if(!compareCodes.includes(code))compareCodes.push(code);renderCompare()};
document.querySelector('#clear-compare-countries').onclick=()=>{compareCodes=[];renderCompare();showToast('تم مسح جميع الدول من المقارنة')};
document.querySelectorAll('.comparison-tab').forEach(btn=>btn.onclick=()=>{compareCategory=btn.dataset.category;document.querySelectorAll('.comparison-tab').forEach(x=>x.classList.toggle('active',x===btn));renderCompare()});
document.querySelector('#compare-package-trip').onchange=e=>{comparePackageTrip=e.target.value;renderCompare()};
document.querySelector('#compare-package-tier').onchange=e=>{comparePackageTier=e.target.value;renderCompare()};
function allPackages(trip='hajj'){const hajj=[{name:'اقتصادية',factor:.78,nights:8,hotel:3,distance:1700,services:'نقل جماعي + وجبتان'},{name:'متوازنة',factor:1,nights:11,hotel:4,distance:850,services:'نقل + 3 وجبات'},{name:'مميزة',factor:1.46,nights:14,hotel:5,distance:350,services:'نقل خاص + إعاشة'}],umrah=[{name:'اقتصادية',factor:.18,nights:5,hotel:3,distance:1400,services:'نقل مشترك'},{name:'متوازنة',factor:.27,nights:8,hotel:4,distance:700,services:'نقل + إفطار'},{name:'مميزة',factor:.41,nights:11,hotel:5,distance:250,services:'نقل خاص + إفطار'}],tiers=trip==='hajj'?hajj:umrah;return Object.entries(marketSeed).flatMap(([code,seed],countryIndex)=>{const m=marketFor(code);return tiers.map((t,tierIndex)=>{const variation=(countryIndex%5)*130+(tierIndex*40),price=Math.round((m.basePrice*t.factor+variation)/50)*50,nights=t.nights+(countryIndex%3),distance=t.distance+(countryIndex%4)*90,hotel=Math.max(2,Math.min(5,t.hotel-(countryIndex%7===0&&tierIndex===0?1:0))),round=x=>Math.round(x/50)*50,components={service:round(price*(.018+(countryIndex%3)*.004)),transport:round(price*(.012+(distance>1000?.009:.003))),lodging:round(price*(.008+(5-hotel)*.004)),extras:round(price*(.006+(tierIndex%2)*.004))},labels={service:'رسوم الخدمة',transport:'النقل الإضافي',lodging:'فرق السكن',extras:'الخدمات الإضافية'},gap=Object.values(components).reduce((s,v)=>s+v,0),actualPaid=price+gap,reason=labels[Object.entries(components).sort((a,b)=>b[1]-a[1])[0][0]];return {code,country:seed.name,trip,tier:t.name,price,actualPaid,gap,gapPct:gap/price*100,reason,components,nights,hotel,distance,services:t.services}})})}
function formulaNote(text){return `<p class="formula-note"><strong>طريقة الحساب:</strong> ${text} <span>جميع قيم الباقات والمكونات بيانات تجريبية وليست مدفوعات فعلية.</span></p>`}
function packageColumnsHTML(rows,limit=6){const top=[...rows].sort((a,b)=>b.gapPct-a.gapPct).slice(0,limit),max=Math.max(...top.map(p=>p.actualPaid),1),showTier=new Set(rows.map(p=>p.tier)).size>1;return `<div class="package-columns"><div class="chart-legend"><span><i class="price-key"></i> السعر المعلن</span><span><i class="paid-key"></i> الدفع الفعلي</span></div><div class="package-column-plot">${top.map(p=>`<div class="package-column-group"><div class="column-pair"><i class="price" style="height:max(12px,${p.price/max*100}%)"><b>${sar(p.price)}</b></i><i class="paid" style="height:max(12px,${p.actualPaid/max*100}%)"><b>${sar(p.actualPaid)}</b></i></div><div class="package-column-meta"><span class="gap-badge">فجوة +${pct(p.gapPct)}</span><strong>${p.country}</strong>${showTier?`<small>${p.tier}</small>`:''}</div></div>`).join('')}</div></div>${formulaNote('الدفع الفعلي = السعر المعلن + رسوم الخدمة + النقل الإضافي + فرق السكن + الخدمات الإضافية. نسبة الفجوة = الفرق ÷ السعر المعلن × 100.')}`}
function costCompositionHTML(rows,limit=5){const top=[...rows].sort((a,b)=>b.gapPct-a.gapPct).slice(0,limit),showTier=new Set(rows.map(p=>p.tier)).size>1;return `<p class="chart-reading"><strong>كيف يُقرأ؟</strong> كل شريط يمثل الزيادة فوق السعر المعلن فقط، وليس كامل سعر الباقة. تقسيم الشريط يوضح أين ذهبت الزيادة بين الخدمة والنقل والسكن والإضافات.</p><div class="cost-legend"><span><i class="service"></i> خدمة</span><span><i class="transport"></i> نقل</span><span><i class="lodging"></i> سكن</span><span><i class="extras"></i> إضافات</span></div><div class="composition-list">${top.map(p=>`<div class="composition-row"><div class="composition-head"><strong>${p.country}${showTier?` · ${p.tier}`:''}</strong><span>المعلن ${sar(p.price)} ← الفعلي ${sar(p.actualPaid)} · زيادة ${sar(p.gap)}</span></div><div class="composition-bar" aria-label="توزيع الزيادة في ${p.country}">${Object.entries(p.components).map(([key,value])=>`<i class="${key}" style="width:${value/p.gap*100}%" title="${sar(value)}"></i>`).join('')}</div><div class="component-values"><span>الخدمة ${sar(p.components.service)}</span><span>النقل ${sar(p.components.transport)}</span><span>السكن ${sar(p.components.lodging)}</span><span>الإضافات ${sar(p.components.extras)}</span></div><small>أكبر مكوّن في الزيادة: ${p.reason}</small></div>`).join('')}</div>${formulaNote('الزيادة = الدفع الفعلي − السعر المعلن. حصة كل مكوّن = قيمة المكوّن ÷ إجمالي الزيادة × 100.')}`}
function renderPackages(){const trip=document.querySelector('#package-trip').value;let rows=allPackages(trip),country=document.querySelector('#package-country').value,tier=document.querySelector('#package-tier').value,sort=document.querySelector('#package-sort').value;rows=rows.filter(p=>(country==='all'||p.code===country)&&(tier==='all'||p.tier===tier));rows.sort(sort==='priceDesc'?(a,b)=>b.actualPaid-a.actualPaid:sort==='distance'?(a,b)=>a.distance-b.distance:sort==='hotel'?(a,b)=>b.hotel-a.hotel:sort==='duration'?(a,b)=>b.nights-a.nights:(a,b)=>a.actualPaid-b.actualPaid);const avg=rows.reduce((s,p)=>s+p.price,0)/(rows.length||1),avgPaid=rows.reduce((s,p)=>s+p.actualPaid,0)/(rows.length||1),avgGap=rows.reduce((s,p)=>s+p.gapPct,0)/(rows.length||1);document.querySelector('#package-summary').innerHTML=`<div class="package-stat"><span>نوع الرحلة</span><strong>${trip==='hajj'?'الحج':'العمرة'}</strong></div><div class="package-stat"><span>متوسط المعلن</span><strong>${sar(avg)}</strong></div><div class="package-stat"><span>متوسط المدفوع</span><strong>${sar(avgPaid)}</strong></div><div class="package-stat"><span>متوسط الفجوة</span><strong>${pct(avgGap)}</strong><small>مجموع نسب الفجوة ÷ عدد الباقات</small></div>`;document.querySelector('#package-gap-analysis').innerHTML=packageColumnsHTML(rows);document.querySelector('#package-drivers').innerHTML=costCompositionHTML(rows);document.querySelector('#package-table').innerHTML=rows.map(p=>`<tr><td>${p.country}</td><td>${p.tier}</td><td>${sar(p.price)}</td><td>${sar(p.actualPaid)}</td><td>${sar(p.gap)} · ${pct(p.gapPct)}</td><td>${number.format(p.nights)} ليالٍ</td><td>${number.format(p.hotel)} نجوم</td><td>${number.format(p.distance)} م</td><td><div class="service-cell"><strong>${p.services}</strong><small>أكبر إضافة: ${p.reason}</small></div></td></tr>`).join('')}
['package-trip','package-country','package-tier','package-sort'].forEach(id=>document.querySelector(`#${id}`).onchange=renderPackages);

function renderDictionary(){const q=document.querySelector('#dictionary-search').value.trim().toLowerCase(),rows=dictionary.filter(d=>!q||String(d.name_ar||'').includes(q)||String(d.column_name||'').toLowerCase().includes(q)||String(d.category_ar||'').includes(q));document.querySelector('#dictionary-list').innerHTML=rows.map(d=>`<div class="dictionary-item"><strong>${d.name_ar||d.column_name}</strong><span>${d.definition_ar||'لا يتوفر تعريف'}</span><small>${d.category_ar||'مؤشر'} · ${d.source_organization_en||d.source_dataset||'World Bank'}</small></div>`).join('')}
document.querySelector('#dictionary-search').oninput=renderDictionary;

function openCountry(code){const c=countryByCode[code];if(!c)return;const m=marketFor(code),general=[['السكان',compact.format(safe(c.population_total)),c.population_total_year],['الناتج المحلي',usd.format(safe(c.gdp_current_usd)),c.gdp_current_usd_year],['دخل الفرد',usd.format(safe(c.gni_per_capita_usd)),c.gni_per_capita_usd_year],['التحضر',pct(safe(c.urban_population_pct)),c.urban_population_pct_year],['مستخدمو الإنترنت',pct(safe(c.internet_users_pct)),c.internet_users_pct_year],['التضخم',pct(safe(c.inflation_pct)),c.inflation_pct_year]];document.querySelector('#country-detail').innerHTML=`<div class="detail-head"><p class="section-number">${code} · ${c.region_name_en||''}</p><h2>${arabicName(c)}</h2><p>${c.country_name_en} · ${c.capital_name_en||'العاصمة غير متاحة'}</p></div><div class="detail-body"><section class="country-data-section general-section"><div class="detail-title-row"><div><span>01</span><h3>المؤشرات العامة</h3></div><small>المصدر: ملف البنك الدولي</small></div><div class="detail-grid">${general.map(x=>`<div class="detail-stat"><span>${x[0]}</span><strong>${x[1]}</strong><small>سنة ${x[2]||'غير متاحة'}</small></div>`).join('')}</div></section>${m?`<section class="country-data-section hajj-section"><div class="detail-title-row"><div><span>02</span><h3>الحج</h3></div><small>بيانات تجريبية · موسم ${season} هـ</small></div><div class="detail-grid">${[['المتقدمون',number.format(m.applicants)],['الحصة',number.format(m.quota)],['الدخول الفعلي',number.format(m.entries)],['استغلال الحصة',pct(m.entries/m.quota*100)]].map(x=>`<div class="detail-stat"><span>${x[0]}</span><strong>${x[1]}</strong><small>موسم ${season} هـ</small></div>`).join('')}</div><div class="detail-note">${pct(m.quota/m.applicants*100)} من المتقدمين تقابلهم حصة، و${pct(m.entries/m.quota*100)} من الحصة تحولت إلى دخول فعلي.</div></section><section class="country-data-section umrah-section"><div class="detail-title-row"><div><span>03</span><h3>العمرة</h3></div><small>بيانات تجريبية · منفصلة عن الحج</small></div><div class="detail-grid two">${[['المعتمرون',compact.format(m.umrah)],['النمو التجريبي',pct(m.growth)]].map(x=>`<div class="detail-stat"><span>${x[0]}</span><strong>${x[1]}</strong><small>موسم ${season} هـ</small></div>`).join('')}</div></section>`:`<div class="detail-note">لا توجد بيانات حج أو عمرة تجريبية لهذه الدولة. يظهر ملف المؤشرات العامة فقط.</div>`}<div class="detail-note">لا تُخلط مؤشرات البنك الدولي مع بيانات الحج والعمرة؛ يظهر المصدر والحالة الزمنية داخل كل قسم.</div></div>`;document.querySelector('#country-dialog').showModal()}
document.querySelector('.dialog-close').onclick=()=>document.querySelector('#country-dialog').close();
document.querySelector('#country-dialog').addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.close()});

function exportCountries(){const rows=currentCountries.length?currentCountries:worldBank,cols=['iso3_code','country_name_en','region_name_en','income_level_name_en','population_total','population_total_year','gdp_current_usd','gdp_current_usd_year','gni_per_capita_usd','gni_per_capita_usd_year'];const csv=[cols.join(','),...rows.map(r=>cols.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(','))].join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`market-countries-${season}.csv`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast(`تم تصدير ${rows.length} سجلًا`)}
document.querySelector('#export-button').onclick=exportCountries;
function renderMarketViews(){document.querySelectorAll('[data-season-label]').forEach(el=>el.textContent=`${season} هـ`);renderOverview();renderHajj();renderUmrah();renderCompare();renderPackages()}

function buildCustomSelect(select){
  if(select.dataset.customized)return;
  select.dataset.customized='true';
  const shell=document.createElement('div');shell.className='custom-select';
  const trigger=document.createElement('button');trigger.type='button';trigger.className='custom-select-trigger';trigger.setAttribute('aria-haspopup','listbox');trigger.setAttribute('aria-expanded','false');
  const menu=document.createElement('div');menu.className='custom-select-menu';menu.setAttribute('role','listbox');
  select.parentNode.insertBefore(shell,select);shell.append(select,trigger,menu);
  const rebuild=()=>{const selected=select.options[select.selectedIndex];trigger.textContent=selected?.textContent||'اختر';menu.innerHTML=[...select.options].map(option=>`<button type="button" role="option" data-value="${option.value.replaceAll('"','&quot;')}" aria-selected="${option.selected}">${option.textContent}</button>`).join('')};
  trigger.onclick=()=>{const open=!shell.classList.contains('open');document.querySelectorAll('.custom-select.open').forEach(x=>{x.classList.remove('open');x.querySelector('.custom-select-trigger')?.setAttribute('aria-expanded','false')});shell.classList.toggle('open',open);trigger.setAttribute('aria-expanded',String(open))};
  menu.onclick=e=>{const option=e.target.closest('[data-value]');if(!option)return;select.value=option.dataset.value;select.dispatchEvent(new Event('change',{bubbles:true}));shell.classList.remove('open');trigger.setAttribute('aria-expanded','false');rebuild()};
  select.addEventListener('change',rebuild);new MutationObserver(rebuild).observe(select,{childList:true,subtree:true});rebuild();
}
function syncCustomSelects(){document.querySelectorAll('select[data-customized]').forEach(select=>select.dispatchEvent(new Event('custom-sync')));document.querySelectorAll('.custom-select').forEach(shell=>{const select=shell.querySelector('select'),trigger=shell.querySelector('.custom-select-trigger'),menu=shell.querySelector('.custom-select-menu'),selected=select.options[select.selectedIndex];trigger.textContent=selected?.textContent||'اختر';menu.querySelectorAll('[data-value]').forEach(option=>option.setAttribute('aria-selected',String(option.dataset.value===select.value)))})}
document.addEventListener('click',e=>{if(!e.target.closest('.custom-select'))document.querySelectorAll('.custom-select.open').forEach(x=>{x.classList.remove('open');x.querySelector('.custom-select-trigger')?.setAttribute('aria-expanded','false')})});
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.custom-select.open').forEach(x=>{x.classList.remove('open');x.querySelector('.custom-select-trigger')?.setAttribute('aria-expanded','false')})});

populateFilters();document.querySelectorAll('select').forEach(buildCustomSelect);renderCountries(true);renderDictionary();renderMarketViews();syncCustomSelects();
